# Generated by Django 4.1.6 on 2023-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='Задача')),
                ('status', models.CharField(choices=[('complete', 'Завершена'), ('new', 'Новая'), ('in_process', 'В процессе')], default='new', max_length=50, verbose_name='Статус задачи')),
                ('completion_date', models.DateField(null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
