# Generated by Django 4.1.6 on 2023-02-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_todoparagraph_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoparagraph',
            name='status',
            field=models.CharField(choices=[('in_process', 'В процессе'), ('complete', 'Завершена'), ('new', 'Новая')], default='new', max_length=50, verbose_name='Статус задачи'),
        ),
    ]
