# Generated by Django 4.1.6 on 2023-02-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_alter_todoparagraph_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoparagraph',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('complete', 'Завершена')], default='new', max_length=50, verbose_name='Статус задачи'),
        ),
    ]
