# Generated by Django 4.1.6 on 2023-02-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_alter_todoparagraph_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoparagraph',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание задачи'),
        ),
    ]
